# Generated by Django 4.0.8 on 2022-10-31 12:39

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_auto_20201126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=cdh.core.fields.encrypted_fields.EncryptedEmailField(blank=True, null=True, verbose_name='participant:attribute:email'),
        ),
    ]
