# Generated by Django 4.2.24 on 2026-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0012_alter_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='anonymized',
            field=models.BooleanField(default=False, verbose_name='participant:attribute:anonymized'),
        ),
    ]
