# Generated by Django 4.2.24 on 2026-06-02 13:27

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_participant_anonymized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dyslexic',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(null=True, verbose_name='participant:attribute:dyslexic'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='language',
            field=cdh.core.fields.encrypted_fields.EncryptedTextField(null=True, verbose_name='participant:attribute:language'),
        ),
    ]
