# Generated by Django 4.2.24 on 2026-06-02 13:27

import cdh.core.fields.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0014_alter_participant_dyslexic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='capable',
            field=cdh.core.fields.encrypted_fields.EncryptedBooleanField(default=True, null=True, verbose_name='participant:attribute:capable'),
        ),
    ]
