# Generated by Django 4.2.23 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0002_alter_leader_api_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
